Repository ssg-240304-java2/shop-notImplement, pull requests merged in 2024-06, with the labels that each got.

#42 init: 프로젝트 초기 디렉토리 및 DB 설정
  build.gradle
  src/main/java/com/ohgiraffers/notimplement/admin/controller/AdminController.java
  src/main/java/com/ohgiraffers/notimplement/product/controller/ProductController.java
  src/main/resources/application.yml
  src/main/resources/static/css/userStyle.css
  src/main/resources/templates/common/fragments/adm/header.html
  src/main/resources/templates/common/fragments/user/header.html
  src/main/resources/templates/userPage/product/productList.html
Labels: ⚙ Type: Setting

#43 setting: Mybatis 설정 추가
  src/main/java/com/ohgiraffers/notimplement/configuration/MybatisConfiguration.java
  src/main/resources/mappers/user.xml
Labels: ⚙ Type: Setting

#44 setting: Mybatis 설정 파일 추가
  src/main/java/com/ohgiraffers/notimplement/configuration/MybatisConfiguration.java
  src/main/resources/mappers/user.xml
Labels: ⚙ Type: Setting

#47 Feat: 고객 적립금 조회 페이지 구현
  src/main/java/com/ohgiraffers/notimplement/product/controller/ProductController.java
  src/main/java/com/ohgiraffers/notimplement/product/model/dao/ProductMapper.java
  src/main/java/com/ohgiraffers/notimplement/product/model/domain/Product.java
  src/main/java/com/ohgiraffers/notimplement/product/model/domain/ProductStatus.java
  src/main/java/com/ohgiraffers/notimplement/product/model/dto/DashBoardResponse.java
  src/main/java/com/ohgiraffers/notimplement/product/service/ProductService.java
  src/main/java/com/ohgiraffers/notimplement/user/controller/UserController.java
  src/main/java/com/ohgiraffers/notimplement/user/model/dao/UserMapper.java
  src/main/java/com/ohgiraffers/notimplement/user/model/service/UserService.java
  src/main/java/com/ohgiraffers/notimplement/user/model/service/UserServiceImpl.java
  src/main/resources/mappers/ProductMapper.xml
  src/main/resources/mappers/UserMapper.xml
  src/main/resources/templates/adminPage/product/productDashboard.html
  src/main/resources/templates/common/fragments/user/header.html
  src/main/resources/templates/common/layouts/userDefault.html
  src/main/resources/templates/userPage/point/point.html
  src/main/resources/templates/userPage/userInfo.html
Labels: ✨ Type: Feature

#57 구매자 주문 배송 조회 기능 구현, 관리자 주문 배송 조회, 상세 정보 조회 가능 구현
  src/main/java/com/ohgiraffers/notimplement/configuration/MybatisConfiguration.java
  src/main/java/com/ohgiraffers/notimplement/order/controller/OrderController.java
  src/main/java/com/ohgiraffers/notimplement/order/model/dao/OrderMapper.java
  src/main/java/com/ohgiraffers/notimplement/order/model/dto/DetailOrderDTO.java
  src/main/java/com/ohgiraffers/notimplement/order/model/dto/OrderDTO.java
  src/main/java/com/ohgiraffers/notimplement/order/model/dto/OrderDeliveryDTO.java
  src/main/java/com/ohgiraffers/notimplement/order/model/service/OrderService.java
  src/main/java/com/ohgiraffers/notimplement/order/model/service/OrderServiceImpl.java
  src/main/resources/mappers/OrderMapper.xml
  src/main/resources/mappers/user.xml
  src/main/resources/templates/adminPage/order/orderDetailsInfo.html
  src/main/resources/templates/adminPage/order/orderInfoLookup.html
  src/main/resources/templates/common/fragments/adm/aside.html
  src/main/resources/templates/userPage/order/orderDeliveryLookup.html
  src/main/resources/templates/userPage/userInfo.html
Labels: Status: Feedback Needed, Status: On Hold

#63 Feat: 1:1문의 기능 개발
  build.gradle
  src/main/java/com/ohgiraffers/notimplement/auth/controller/AuthController.java
  src/main/java/com/ohgiraffers/notimplement/board/controller/FileController.java
  src/main/java/com/ohgiraffers/notimplement/board/controller/InquiryController.java
  src/main/java/com/ohgiraffers/notimplement/board/model/dao/InquiryMapper.java
  src/main/java/com/ohgiraffers/notimplement/board/model/dto/BoardDTO.java
  src/main/java/com/ohgiraffers/notimplement/board/model/dto/FileDTO.java
  src/main/java/com/ohgiraffers/notimplement/board/model/service/FileUploadService.java
  src/main/java/com/ohgiraffers/notimplement/board/model/service/InquiryService.java
  src/main/resources/application.yml
  src/main/resources/mappers/board/InquiryMapper.xml
  src/main/resources/templates/adminPage/board/inquiryDetail.html
  src/main/resources/templates/adminPage/board/inquiryList.html
  src/main/resources/templates/adminPage/main.html
  src/main/resources/templates/common/fragments/adm/aside.html
  src/main/resources/templates/common/fragments/user/header.html
  src/main/resources/templates/common/layouts/admDefault.html
  src/main/resources/templates/common/layouts/userDefault.html
  src/main/resources/templates/userPage/board/test.html
  src/main/resources/templates/userPage/board/testDisplay.html
Labels: ✨ Type: Feature

#65 !HOTFIX: 로그인 기능 버그 수정
  src/main/java/com/ohgiraffers/notimplement/auth/controller/AuthController.java
  src/main/resources/mappers/user.xml
  src/main/resources/static/index.html
Labels: 🐞 Type: Bug

#67 fix: 주문/배송상태 조회 오류 수정
  src/main/java/com/ohgiraffers/notimplement/order/controller/OrderController.java
  src/main/java/com/ohgiraffers/notimplement/order/model/dao/OrderMapper.java
  src/main/java/com/ohgiraffers/notimplement/order/model/service/OrderServiceImpl.java
  src/main/resources/mappers/OrderMapper.xml
  src/main/resources/templates/userPage/order/orderDeliveryLookup.html
Labels: 🐞 Type: Bug

#69 feat: 관리자 배송 조회 및 배송 상태 변경 기능 구현
  src/main/java/com/ohgiraffers/notimplement/delivery/controller/DeliveryController.java
  src/main/java/com/ohgiraffers/notimplement/delivery/model/dao/DeliveryMapper.java
  src/main/java/com/ohgiraffers/notimplement/delivery/model/dto/DeliveryDTO.java
  src/main/java/com/ohgiraffers/notimplement/delivery/model/service/DeliveryService.java
  src/main/java/com/ohgiraffers/notimplement/delivery/model/service/DeliveryServiceImpl.java
  src/main/java/com/ohgiraffers/notimplement/delivery/paging/DeliveryPagenation.java
  src/main/java/com/ohgiraffers/notimplement/delivery/paging/SelectDeliveryCriteria.java
  src/main/resources/mappers/DeliveryMapper.xml
  src/main/resources/templates/adminPage/delivery/deliveryManagement.html
  src/main/resources/templates/common/fragments/adm/aside.html
Labels: ✨ Type: Feature

#71 Feat: 고객 배송 상태 조회 기능 구현
  src/main/resources/mappers/OrderMapper.xml
Labels: ✨ Type: Feature

#72 fix : login 및 logout 수정
  src/main/java/com/ohgiraffers/notimplement/auth/controller/AuthController.java
  src/main/resources/static/index.html
  src/main/resources/templates/common/fragments/adm/aside.html
  src/main/resources/templates/common/fragments/adm/header.html
  src/main/resources/templates/common/fragments/user/header.html
Labels: 🐞 Type: Bug, ✨ Type: Feature

#75 Feat: 접속 고객 session에서 user_id 불러오는 기능 구현
  src/main/java/com/ohgiraffers/notimplement/user/controller/UserController.java
  src/main/java/com/ohgiraffers/notimplement/user/model/dao/UserMapper.java
  src/main/java/com/ohgiraffers/notimplement/user/model/service/UserService.java
  src/main/java/com/ohgiraffers/notimplement/user/model/service/UserServiceImpl.java
  src/main/resources/mappers/UserMapper.xml
Labels: ✨ Type: Feature

#76 주문서 작성 기능 구현 완료
  src/main/java/com/ohgiraffers/notimplement/order/controller/OrderController.java
  src/main/java/com/ohgiraffers/notimplement/order/model/dao/OrderMapper.java
  src/main/java/com/ohgiraffers/notimplement/order/model/dto/ProcessOrderDTO.java
  src/main/java/com/ohgiraffers/notimplement/order/model/service/OrderService.java
  src/main/java/com/ohgiraffers/notimplement/order/model/service/OrderServiceImpl.java
  src/main/resources/mappers/OrderMapper.xml
  src/main/resources/templates/userPage/order/processOrder.html
  src/main/resources/templates/userPage/product/product-details.html
Labels: Status: Complete
